### PR TITLE
Fixed initial migration with updated help text

### PR DESCRIPTION
**Pull request by macdiesel**
@nedbat @doctoryes @symbolist This PR is to fix the migration issues @andy-armstrong and @frrrances was seeing this morning in dev chat.

### CODE REVIEW

**Comment by macdiesel** [comment]
@nedbat @doctoryes @symbolist This PR is to fix the migration issues @andy-armstrong and @frrrances was seeing this morning in dev chat.

**Comment by macdiesel** [comment]
relevant link: https://stackoverflow.com/questions/26503826/why-does-django-generate-migrations-for-help-text-and-verbose-name-changes

**Comment by doctoryes** [comment]
:arrow_backward: Change help text in intial migration :arrow_forward: 

:+1:

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
