### PR TITLE
SOL-1212-Org

### PR DESCRIPTION
**Pull request by asadiqbal08**
@ziafazal @mattdrayer small change.

### CODE REVIEW

**Comment by ziafazal** [comment]
:+1:

**Comment by mattdrayer** [comment]
@asadiqbal08 -- please also be sure to increment the setup.py package version and include in this PR.  After we merge we'll need to create a new release tag for this repository and then submit an additional PR to the edx-platform repository which updates the edx-organizations package reference in github.txt.

With the updated setup.py package version we can shift the edx-organizations reference to non-editable, which I wanted to do in this incomplete PR -- https://github.com/edx/edx-platform/pull/9300 -- but now maybe you can finish the job for real.

**Comment by asadiqbal08** [comment]
@ziafazal can you please look at the version that i incremented and as @mattdrayer suggested above ? 
thanks

**Comment by mattdrayer** [comment]
@asadiqbal08, I am good with the version change -- merging, and you can now update the reference in edx-platform -- please reference https://github.com/edx/edx-platform/pull/9300 for an example of what needs to be done.  I will close 9300 after your PR has been submitted.

**Comment by mattdrayer** [comment]
Added the release tag for you:  https://github.com/edx/edx-organizations/releases/tag/release-2015-09-16

**Pull request merged**
