### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@edx/solutions: I'm marking you as the owner of this repo.

**Comment by mattdrayer** [comment]
Hmm, it probably makes sense to transfer ownership of this repo to the @edx/teaching-and-learning team?

**Comment by cpennington** [comment]
@edx/teaching-and-learning: Are you folks ok w/ owning this repo?

**Comment by cahrens** [comment]
This isn't Ecom?

@scottrish I have not heard anything about us owning "organizations". Can you confirm?

**Comment by nedbat** [comment]
Closing in favor of #47

**Pull request closed without merging**
