### PR TITLE
Upgrade to Django 1.8

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by mattdrayer** [comment]
:+1:

**Comment by mattdrayer** [comment]
@nedbat -- did you need me to merge this PR?

**Comment by nedbat** [comment]
@mattdrayer no, don't merge any Django 1.8 upgrades yet.  We need to coordinate across repos.

**Comment by macdiesel** [comment]
@mattdrayer We are working on merging all the django 1.8 changes back to their master/release branches. Still good to bring this in?

**Pull request merged**
