### PR TITLE
register the organization models with admin interface

### PR DESCRIPTION
**Pull request by asadiqbal08**
@mattdrayer kindly look into that change set. we need to update the release / commit hash in github.txt as well

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@mattdrayer let me know one thing, should we need to override the delete behavior for Admin page OR used the default one ?  I mean, what you suggest if we softly delete the organization (By marking the active flag to false ) ?

**Comment by mattdrayer** [comment]
@asadiqbal08 -- looks like we're on the right track here -- I do think it's important to preserve the soft-delete behavior, so yes we should override the default delete behavior by adding a custom action to the admin.  See this StackOverflow article for more information on how to do this:  http://stackoverflow.com/questions/15196313/django-admin-override-delete-method  Also here is a link to the Django 1.4 documentation: https://docs.djangoproject.com/en/1.4/ref/contrib/admin/actions/

**Comment by mattdrayer** [comment]
Also looks like we need some test coverage for the new admin.py module and model updates

**Comment by asadiqbal08** [comment]
@mattdrayer can you please look into the changes now ? 
I need to look around the test cases yet.

**Comment by mattdrayer** [comment]
Fantastic -- this is looking really good imho -- so we just need to add the proper test coverage and address the pylint violations, then we should be in good shape with this aspect of the story.  Nice work!

**Comment by asadiqbal08** [comment]
@mattdrayer I have done with this PR. your final review will be helpful for me. 

@ziafazal you can use this commit hast in github.txt if required. 
Thank you.

**Comment by mattdrayer** [comment]
Code looks great!  Thanks for adding the test coverage -- very happy about how this is turning out :)  :+1:

**Pull request merged**
