### PR TITLE
Relax django-model-utils constraint (edx-platform uses 2.3.1)

### PR DESCRIPTION
**Pull request by cpennington**
@clintonb: Care to review?

### CODE REVIEW

**Comment by cpennington** [comment]
@cahrens, @mattdrayer: I'm pinging both of you as well, since the ownership of this repo is unknown.

**Comment by cahrens** [comment]
Don't think organizations belongs to TNL. I recall talking to @mattdrayer about it about a year ago....

**Comment by cpennington** [comment]
@clintonb: `edx-platform` should be doing the pinning (which it is), rather than the django app itself doing the pinning (like it is now).

**Comment by mattdrayer** [comment]
I can't say anyone really "owns" this repo at present.  The change seems innocuous, although checks are failing...

**Comment by cpennington** [comment]
Someone needs to own it.

@mattdrayer: I'm declaring solutions the owner by fiat, because you have clients that depend on it working (and I don't believe edx.org actually uses it).

**Comment by mattdrayer** [comment]
You can try to do that, but I would actually argue that whoever owns credentials/certificates should also own organizations, because that's how it's being used 😄 .  I'm not sure who owns creds/certs, tho.

**Comment by clintonb** [comment]
This change will be captured when #30 is merged.

ECOM "owns" credentials because we built the Credentials Service; however, we have not touched certificates in LMS and we do not make use of this package in the Credentials Service. We are not claiming ownership of this repository.

Personally, I see no reason for this repo to exist. It is useless without LMS, so it doesn't really make sense for it to live outside of edx/edx-platform.

**Pull request closed without merging**
